name: Sync fork with upstream

on:
  schedule:
    # 每天北京时间 09:00
    - cron:  "0 19 * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Sync fork
        run: |
          gh repo sync zz-zed/reverse-skill \
            --source zhaoxuya520/reverse-skill \
            --force
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
